# # Classifiers comparison on texts with naive Bayes assumption

In this session of laboratory we compare two models for categorical data probabilistic modeling: 
1. multivariate Bernoulli 
2. multinomial on a dataset 

We adopt a dataset on Twitter messages labelled with emotions (Joy vs Sadness).

The following program shows the loading of the data from a file.

Data are loaded into a matrix X adopting a sparse matrix representation, in order to save space and time.
Sparse matrix representation (in the csr format) represents in three "parallel" arrays the value of the matrix cells that are different from zero and the indices of those matrix cells.
The arrays are called: 
- data
- row
- col

- data[i] stores the value of the matrix cell #i whose indexes are contained in row[i] and col[i] 
- row[i] stores the index of the row in the matrix of the cell #i, 
- col[i] stores the index of the column of the cell #i.


The data file is in csv format.
Any Twitter message has been preprocessed by a Natural Language pipeline which eliminated stop words and substituted the interesting document elements with an integer identifier.  
The interesting document elements might be words, emoji or emoticons. The elements could be repeated in the same document and are uniquely identified in the documents by the same integer number (named "element_id" in the program). This "element_id" number will be used as the index of the column of the data matrix, for the purposes of storage of data.

Each row of the CSV file reports the content of a document (a Twitter message).It is formed as a list of integer number pairs, followed by a string which is the label of the document ("Joy" or "Sadness").
The first number of the pair is the identifier of a document element (the "element_id"); 
the second number of the pair is the count (frequency) of that element in that document.

The dataset has:

tot_n_docs (or rows in the file) =n_rows=11981

n_features (total number of distinct words in the corpus)=11288



The following program reads the data file and loads in a sparse way the matrix using the scipy.sparse library

In [ ]:

from numpy import ndarray, zeros
import numpy as np
import scipy
from scipy.sparse import csr_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score


class_labels = ["Joy","Sadness"]
n_features=11288 # number of columns in the matrix = number of features (distinct elements in the documents)
n_rows=11981 # number rows of the matrix
n_elements=71474 # number of the existing values in the matrix (not empty, to be loaded in the matrix in a sparse way) (# totale di elementi nell'array)

#path_training="/Users/meo/Documents/Didattica/Laboratorio-15-16-Jupyter/"
#path_training="./"
#path_training="/content/Dataset_twitter_emotions/"


path_training="/content/drive/MyDrive/Colab Notebooks/Datasets-AA/"
file_name="joy_sadness6000.txt"



# declare the row and col arrays with the indexes of the matrix cells (non empty) to be loaded from file
# they are needed because the matrix is sparse and we load in the matrix only the elements which are present
row=np.empty(n_elements, dtype=int)
col=np.empty(n_elements, dtype=int)
data=np.empty(n_elements, dtype=int)

row_n=0 # number of current row to be read and managed
cur_el=0 # position in the three arrays: row, col and data
twitter_labels=[] # list of class labels (target array) of the documents (twitter) that will be read from the input file
twitter_target=[] # list of 0/1 for class labels

with open(path_training + file_name, "r") as fi:

    #legge una riga del file alla volta
    for line in fi:
        el_list=line.split(',')  # list of integers read from a row of the file
        l=len(el_list)
        last_el=el_list[l-1] # I grab the last element in the list which is the class label
        class_name=last_el.strip() # eliminate the '\n'
        twitter_labels.append(class_name)
        # twitter_labels contains the labels (Joy/Sadness); twitter_target contains 0/1 for the respective labels
        if (class_name==class_labels[0]):
           twitter_target.append(0)
        else:
           twitter_target.append(1)
        i=0 # I start reading all the doc elements from the beginning of the list
        while(i<(l-1)):
            element_id=int(el_list[i]) # identifier of the element in the document equivalent to the column index
            element_id=element_id-1 # the index starts from 0 (the read id starts from 1)
            i=i+1
            value_cell=int(el_list[i]) # make access to the following value in the file which is the count of the element in the document 
            i=i+1
            row[cur_el]=row_n # load the data in the three arrays: the first two are the row and col indexes; the last one is the matrix cell value
            col[cur_el]=element_id
            data[cur_el]=value_cell
            cur_el=cur_el+1
        row_n=row_n+1


fi.close
print("final n_row="+str(row))

# loads the matrix by means of the indexes and the values in the three arrays just filled
twitter_data=csr_matrix((data, (row, col)), shape=(n_rows, n_features)).toarray()
print("resulting matrix:")
print(twitter_data)

print("22-esimo documento: ", twitter_data[21][106])

print("")

print("twitter_labels:")
print(twitter_labels)

print("")
print("twitter_target: ")
print(twitter_target)


final n_row=[0 0 0 ... 0 0 0]
resulting matrix:
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
22-esimo documento:  2

twitter_labels:
['Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Write a program in the following cell that splits the data matrix in training and test set (by random selection) and predicts the class (Joy/Sadness) of the messages on the basis of the words. 
Consider the two possible models:
multivariate Bernoulli and multinomial Bernoulli.
Find the accuracy of the models and test is the observed differences are significant.

In [ ]:

from scipy import stats


# creo la partizione per il train e il test:
X_train, X_test, y_train, y_test = train_test_split(twitter_data, twitter_target, test_size=0.30, shuffle = True, random_state=42)
modello_Multivariato = BernoulliNB()
modello_Multinomiale = MultinomialNB()

#Addestramento modelli:
modello_Multivariato.fit(X_train, y_train)
modello_Multinomiale.fit(X_train, y_train)



#Valutazione modelli:
p_train_Multivariato = modello_Multivariato.predict(X_train)
p_train_Multinomiale = modello_Multinomiale.predict(X_train)

p_test_Multivariato = modello_Multivariato.predict(X_test)
p_test_Multinomiale = modello_Multinomiale.predict(X_test)

train_score_Multivariato = accuracy_score(p_train_Multivariato, y_train)
train_score_Multinomiale = accuracy_score(p_train_Multinomiale, y_train)

test_score_Multivariato = accuracy_score(p_test_Multivariato, y_test)
test_score_Multinomiale = accuracy_score(p_test_Multinomiale, y_test)

print("")
print("Accuratezza modello Multivariato: ")
print("Train: ", train_score_Multivariato)
print("Test: ", test_score_Bernoulli)
print("")
print("Accuratezza modello Multinomiale: ")
print("Train: ", train_score_Multivariato)
print("Test: ", test_score_Multinomiale)

scores_Multivariato = cross_val_score(modello_Multivariato, twitter_data, twitter_target, cv=10)
scores_Multinomiale = cross_val_score(modello_Multinomiale, twitter_data, twitter_target, cv=10)

print("")
print("Accuratezza su ogni fold Multivariato: ", scores_Multivariato)
print("Accuratezza su ogni fold Multinomiale: ", scores_Multinomiale)
print("")
print("Differenze di accuratezza su ogni fold: ", scores_Multivariato-scores_Multinomiale)


#Test di Student:

#ipotesi nulla = le medie delle accuratezze dei due modelli sono uguali.
#10 - 1 = 9 gradi di libertà e alfa=0.05 -> valore critico = 2.262
alfa = 0.05

results = stats.ttest_rel(scores_Multivariato, scores_Multinomiale)
print("")
print("p-value: ", results.pvalue)
print("t-value: ", results.statistic) # t-value = 3.21 > valore critico
print("")

if(results.pvalue < alfa):
  print("L'ipotesi nulla è rifiutata perchè le differenze sono statisticamente significative.")
else:
  print("L'ipotesti nulla non può essere rifiutata perchè le differenze non sono statisticamente significative.")







Accuratezza modello Multivariato: 
Train:  0.9761507274028142
Test:  0.9504867872044507

Accuratezza modello Multinomiale: 
Train:  0.9761507274028142
Test:  0.9471488178025035

Accuratezza su ogni fold Multivariato:  [0.95663053 0.96577629 0.94991653 0.94991653 0.94824708 0.9524207
 0.95075125 0.95492487 0.9624374  0.93656093]
Accuratezza su ogni fold Multinomiale:  [0.95412844 0.96494157 0.94991653 0.94824708 0.94407346 0.94741235
 0.9490818  0.94991653 0.96160267 0.93739566]

Differenze di accuratezza su ogni fold:  [ 0.00250209  0.00083472  0.          0.00166945  0.00417362  0.00500835
  0.00166945  0.00500835  0.00083472 -0.00083472]

p-value:  0.010617994606921194
t-value:  3.2123990690558073

L'ipotesi nulla è rifiutata perchè le differenze sono statisticamente significative.
